"""Mealplan tables

Revision ID: 2893a349df32
Revises: 35428579ed53
Create Date: 2020-03-19 17:32:34.556637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2893a349df32'
down_revision = '35428579ed53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_info',
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('meal_name', sa.String(length=64), nullable=True),
    sa.Column('cal_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('meal_id')
    )
    op.create_index(op.f('ix_meal_info_meal_name'), 'meal_info', ['meal_name'], unique=False)
    op.create_table('mealplan',
    sa.Column('mealplan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('week_date', sa.String(length=64), nullable=True),
    sa.Column('day_no', sa.Integer(), nullable=True),
    sa.Column('total_daily_cal', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.user_id'], ),
    sa.PrimaryKeyConstraint('mealplan_id')
    )
    op.create_index(op.f('ix_mealplan_day_no'), 'mealplan', ['day_no'], unique=False)
    op.create_index(op.f('ix_mealplan_week_date'), 'mealplan', ['week_date'], unique=False)
    op.create_table('mealplan_detail',
    sa.Column('mealplandetail_id', sa.Integer(), nullable=False),
    sa.Column('mealplan_id', sa.Integer(), nullable=True),
    sa.Column('meal_id', sa.Integer(), nullable=True),
    sa.Column('meal_type', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['meal_id'], ['meal_info.meal_id'], ),
    sa.ForeignKeyConstraint(['mealplan_id'], ['mealplan.mealplan_id'], ),
    sa.PrimaryKeyConstraint('mealplandetail_id')
    )
    op.create_index(op.f('ix_mealplan_detail_meal_type'), 'mealplan_detail', ['meal_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mealplan_detail_meal_type'), table_name='mealplan_detail')
    op.drop_table('mealplan_detail')
    op.drop_index(op.f('ix_mealplan_week_date'), table_name='mealplan')
    op.drop_index(op.f('ix_mealplan_day_no'), table_name='mealplan')
    op.drop_table('mealplan')
    op.drop_index(op.f('ix_meal_info_meal_name'), table_name='meal_info')
    op.drop_table('meal_info')
    # ### end Alembic commands ###
