"""UserProfile Table

Revision ID: 35428579ed53
Revises: 
Create Date: 2020-03-18 20:42:36.389357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35428579ed53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=64), nullable=True),
    sa.Column('lname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('profession', sa.String(length=80), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profile_email'), 'user_profile', ['email'], unique=True)
    op.create_index(op.f('ix_user_profile_fname'), 'user_profile', ['fname'], unique=False)
    op.create_index(op.f('ix_user_profile_lname'), 'user_profile', ['lname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profile_lname'), table_name='user_profile')
    op.drop_index(op.f('ix_user_profile_fname'), table_name='user_profile')
    op.drop_index(op.f('ix_user_profile_email'), table_name='user_profile')
    op.drop_table('user_profile')
    # ### end Alembic commands ###
