"""empty message

Revision ID: 6009c076e823
Revises: ac984985a560
Create Date: 2020-03-25 23:18:55.215975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6009c076e823'
down_revision = 'ac984985a560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mealplan', sa.Column('mealplan_name', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_mealplan_mealplan_name'), 'mealplan', ['mealplan_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mealplan_mealplan_name'), table_name='mealplan')
    op.drop_column('mealplan', 'mealplan_name')
    # ### end Alembic commands ###
