"""Changed Table 'MealPlan' - Field day_no from int to string

Revision ID: ac984985a560
Revises: 2893a349df32
Create Date: 2020-03-22 20:32:38.577824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac984985a560'
down_revision = '2893a349df32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_index(op.f('ix_mealplan_day_name'), 'mealplan', ['day_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mealplan_day_name'), table_name='mealplan')
    # ### end Alembic commands ###
