"""Added Status Column to MealPlan

Revision ID: e1a82fe761f5
Revises: 2893a349df32
Create Date: 2020-04-24 21:44:51.559532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1a82fe761f5'
down_revision = '2893a349df32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mealplan', sa.Column('status', sa.String(length=1), nullable=True))
    op.create_index(op.f('ix_mealplan_status'), 'mealplan', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mealplan_status'), table_name='mealplan')
    op.drop_column('mealplan', 'status')
    # ### end Alembic commands ###
